name: Hello World Workflow

on:
  repository_dispatch:
    types: ["hello-world-trigger"]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
